displayName attribute added
foglamp/foglamp-south-mqtt-sparkplug pull request #4
Opened 2019-03-26 06:15 UTC by ashish-jabble

2019-03-28 11:23 UTC, praveen-garg requested changes

2019-03-28 11:23 UTC, praveen-garg commented on python/foglamp/plugins/south/mqtt_sparkplug/mqtt_sparkplug.py
> +        'displayName': 'Topic Name'
`Topic` only

2019-03-28 11:23 UTC, praveen-garg commented on python/foglamp/plugins/south/mqtt_sparkplug/mqtt_sparkplug.py
> +        'displayName': 'URL'
as we have port as another key, it should have been been host, atleast we should say so in displayName `MQTT Host`

2019-03-28 11:23 UTC, praveen-garg commented on python/foglamp/plugins/south/mqtt_sparkplug/mqtt_sparkplug.py
> +        'displayName': 'Port'
`MQTT Port`

2019-04-05 12:01 UTC, praveen-garg approved these changes

2019-04-05 15:45 UTC, MarkRiddoch approved these changes

2019-04-05 15:46 UTC, merged